# Generated by Django 4.2.11 on 2024-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_avatar_creation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileEditModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=2000, null=True)),
                ("file", models.FileField(upload_to="image_media")),
            ],
        ),
    ]
